//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelTamagotchi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotelroom
    {
        public Hotelroom()
        {
            this.Tamagotchi = new HashSet<Tamagotchi>();
        }
    
        public int Roomnumber { get; set; }
        public string Roomtype { get; set; }
        public int Beds { get; set; }
    
        public virtual Roomtype Roomtype1 { get; set; }
        public virtual ICollection<Tamagotchi> Tamagotchi { get; set; }
    }
}
