//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelTamagotchi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roomtype
    {
        public Roomtype()
        {
            this.Hotelroom = new HashSet<Hotelroom>();
        }
    
        public string Roomtype1 { get; set; }
    
        public virtual ICollection<Hotelroom> Hotelroom { get; set; }
    }
}
