//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelTamagotchi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tamagotchi
    {
        public Tamagotchi()
        {
            this.Hotelroom = new HashSet<Hotelroom>();
        }
    
        public string Name { get; set; }
        public int Age { get; set; }
        public int Coins { get; set; }
        public int Level { get; set; }
        public int Health { get; set; }
        public int Boredom { get; set; }
    
        public virtual ICollection<Hotelroom> Hotelroom { get; set; }
    }
}
